apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nginx
        ports:
        - containerPort: 8080 # Assuming your app runs on port 8080
---
apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80 # Expose your service on port 80
      targetPort: 8080
  type: NodePort # Expose the service using NodePort
